name: integration-test
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  integration-test:
    strategy:
      matrix:
        go: [stable]
        os: [ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Run integration test
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: make integration-test
